- name: Enable Auditd Service
  service:
    name: auditd
    state: started
    enabled: yes

- name: Configure Auditd Rules
  template: 
    src: templates/audit/ansible.rules
    dest: /etc/audit/ansible.rules
    owner: root
    group: root
    mode: 0700

 
