- name: Install Audit Package
  package:
    name: audit
    state: installed

- name: Enable Auditd Service
  service:
    name: auditd
    state: started
    enabled: yes

- name: Configure Auditd Settings
  template:
    src: templates/audit/auditd.conf
    dest: /etc/audit/auditd.conf
    owner: root
    group: root
    mode: 0600 

- name: Configure Auditd Rules
  template: 
    src: templates/audit/nss.rules
    dest: /etc/audit/rules.d/nss.rules
    owner: root
    group: root
    mode: 0600

 
