- name: Install Audit Package
  package:
    name: audit
    state: installed

- name: Enable Auditd Service
  service:
    name: auditd
    state: started
    enabled: yes

- name: Configure Auditd Settings
  template:
    src: templates/etc/audit/auditd.conf
    dest: /etc/audit/auditd.conf
    owner: root
    group: root
    mode: 0600 

- name: Configure Auditd Rules
  template: 
    src: templates/etc/audit/nss.rules
    dest: /etc/audit/rules.d/rules.conf
    owner: root
    group: root
    mode: 0600

- name: Auditd File Context Rule (SELinux)
  sefcontext:
    target: '/var/log/audit(/.*)?'
    setype: auditd_log_t
    state: present
    reload: yes



 
