- name: Create admin group
  group:
    name: "{{ base.admin_group }}"
    state: present

- name: Install issue file
  template:
   dest: /etc/issue
   src: templates/etc/issue
   owner: root
   group: "{{ base.admin_group }}"
   mode: 0664

- name: Install cron.allow file
  template:
   dest: /etc/cron.allow
   src: templates/etc/cron.allow
   owner: root
   mode: 0600


