- name: Create admin group
  group:
    name: "{{ base.admin_group }}"
    state: present

- name: Install issue file
  template:
   dest: /etc/issue
   src: templates/etc/issue
   owner: root
   group: "{{ base.admin_group }}"
   mode: 0664

- name: Create support users
  user:
    name: "{{ item }}"
    group: "{{ base.admin_group }}"
    state: present
    append: yes
  with_items:
    - "{{ base.admin_users }}"

- name: Restrict Cron Usage
  file:
    path: /etc/cron.deny
    state: absent

- name: Set up cron.allow
  template:
    dest: /etc/cron.allow
    src: templates/etc/cron.allow
    owner: root
    group: support
    mode: 0660
