- name: Install Parted
  package:
    name: parted
    state: installed

- name: Configure Disk
  parted:
    device: /dev/{{ lvm.ec2_extra_disk }}
    number: 1

- name: Create System Volume Group
  lvg:
    vg: vg.system
    pvs: "/dev/{{ ec2-extra-disk }}/1"

- name: Create Auditd Logical Volumes
  lvol:
    vg: vg.system
    lv: audit
    size: 1024
  when: global_config.configure_auditd == True

- name: Create Auditd LV Filesystem
  filesystem:
    fstype: xfs
    dev: /dev/mapper/vg.system/audit
  when: global_config.configure_auditd == True



