- import_tasks: base.yml

- import_tasks: logging.yml
  tags:
      - log
  when: global_config.configure_logging == True
  
- import_tasks: sshd.yml
  tags:
      - ssh
  when: global_config.sshd_config_file == True

- import_tasks: packages.yml
  tags:
      - packages

- import_tasks: selinux.yml
  tags:
      - selinux
  when: global_config.enable_selinux == True

- import_tasks: auditd.yml
  tags:
      - auditd
  when: global_config.configure_auditd == True


- name: SELinux-required Reboot
  command: /sbin/shutdown -r +1
  when: global_config.selinux_restart == True


