- import_tasks: base.yml

- import_tasks: sshd.yml
  tags:
      - ssh
  when: global_config.sshd_config_file == True

- import_tasks: packages.yml
  tags:
      - packages

- import_tasks: selinux.yml
  tags:
      - selinux
  when: global_config.enable_selinux == True

- import_tasks: auditd.yml
  tags:
      - auditd
  when: global_config.configure_auditd == True

- import_tasks: lvm.yml
  tags:
      - lvm

  when: global_config.configure_lvm == True
