- name: Enable GPG Checks of Repos
  block:
    - find:
        path: /etc/yum.repos.d/
        patterns: '*.repo'
        recurse: yes
      register: find_filepaths
    - lineinfile:
        path: "{{ item.path }}"
        regexp: '^gpgcheck='
        line: 'gpgcheck=1'
        state: present
      with_items: "{{ find_filepaths.files }}" 
  when: config.enable_repo_gpgcheck == True

- name: Enable EPEL Repo
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: True
  when: ansible_os_family == "RedHat" and config.enable_epel_repo == True
