- block:
    - find:
        path: /etc/yum.repos.d/
        patterns: '*.repo'
        recurse: yes
      register: find_filepaths
    - name: Enable GPG Checks of Repos
      lineinfile:
        path: "{{ item.path }}"
        regexp: '^gpgcheck='
        line: 'gpgcheck=1'
        state: present
      with_items: "{{ find_filepaths.files }}" 
  when: global_config.enable_repo_gpgcheck == True

- block:
    - name: Install EPEL Release
      package:
        name: epel-release
        state: installed
  rescue:
    - debug:
        msg: "No package available, defaulting to EPEL package from Fedora"
    - command: '/usr/bin/rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm'
  when: ansible_os_family == "RedHat" and global_config.enable_epel_repo == True

- block:
  - name: Create Logging Directory for Security Packages
    file:
      path: "{{ packages.security_packages_log_dir }}"
      owner: root
      group: "{{ base.admin_group }}"
      mode: 770
      state: directory

  - name: Copy Logrotate Templates
    template:
      src: templates/etc/logrotate.d/security-updates
      dest: /etc/logrotate.d/
      owner: root
      group: "{{ base.admin_group }}"

  - name: Add Security Update Cronjob
    cron:
      name: Automate Security Packages
      hour: 0
      minute: 0
      weekday: 1
      job: yum -y --security update >> /var/log/security-packags/$(date -I)
      state: present
      user: root
      cron_file: security-updates
  when: packages.automate_security_packages == True
