- name: SSHD File Configuration
  template:
      src: templates/ssh/sshd_config
      dest: /etc/ssh/sshd_config
      owner: root
  when:  global_config.sshd_config_file == True 

- name: Restart SSHD
  service:
      name: sshd
      state: restarted
  when: global_config.sshd_service_restart == True




