config:
    sshd_config_file: True
    sshd_service_restart: True
    enable_repo_gpgcheck: True
    enable_epel_repo: True

sshd_config:
   PermitEmptyPasswords: 'no'
   Protocol: 2
   PasswordAuthentication: 'no'
   PermitUserEnvironment: 'no'
   HostbasedAuthentication: 'no'
   Ciphers: 'aes128-ctr,aes192-ctr,aes256-ctr'
   Banner: '/etc/issue'
   ClientAliveInterval: 600
   RhostsRSAAuthentication: 'no'
   ClientAliveCountMax: '0'
   IgnoreRhosts: 'yes'
   PrintLastLog: 'yes'
   PermitRootLogin: 'yes'
   IgnoreUserKnownHosts: 'yes'
   MACs: 'hmac-sha2-256,hmac-sha2-512'
   GSSAPIAuthentication: 'no'
   KerberosAuthentication: 'no'
   StrictModes: 'yes'
   UsePrivilegeSeparation: 'yes'
   Compression: 'delayed'

packages:
    automate_security_packages: True
    security_packages_log_dir: "/var/log/security-packages/"
    security_packages_log_rotate_count: 1
    security_packages_log_rotate_interval: monthly
    security_packages_log_rotate_extra_entries: |
         missingok
         compress 
