---
- name: (Rlogin,Rsh,Rexec) Remove Host-Based Authentication Files
  block:
    - find:
        path: /
        patterns: 'shosts.equiv'
        recurse: yes
      register: shosts_equiv
    - name: (Rlogin,Rsh,Rexec) Remove Host-Based Authentication Files
      file:
        path: "{{ shosts_equiv.files }}"
        state: absent

- name: (Rlogin,Rsh,Rexec) Remove User Host-Based Authentication Files
  block:
    - find:
        path: /home/
        pattern: '.shosts'
        recurse: yes
        depth: 2
      register: shosts_user
    - name: (Rlogin,Rsh,Rexec) Remove User Host-Based Authentication Files
      file:
        path: "{{ shosts_user.files }}"
        state: absent
  
- name: (Rlogin,Rsh,Rexec) Uninstall rsh-server Package
  package:
      name: rsh-server
      state: absent

- name: (Telnet) Uninstall telnet-server Package
  package:
      name: telnet-server
      state: absent

- name: (NIS) Uninstall ypserv Package
  package:
      name: ypserv
      state: absent

- name: (TFTP Server) Uninstall tftp-server Package
  package:
      name: tftp-server
      state: absent

